#862jq9qw1   dane do wyświetlenia studentów
git-asia/HeadHunter_server pull request #17
Opened 2023-05-01 16:20 UTC by JaskierBard

kod nie jest idealnie skończony (zawiera jeden typ any i ogólnie można go dużo lepiej otypować) ale wszystkie założone filtry działają i są zrobione bardziej pod makietę niż specyfikacje bo ta miejscami jest dla mnie nadal niezrozumiała.  Nie wiem ile czasu będę miał do czwartku żeby to polepszyć więc myślę że po ogólnym code review dać merga i pokazać to na demie a później najwyżej fixem  to otypować zanim Kuba będzie sprawdzał.

2023-05-02 12:35 UTC, git-asia commented
Jak dla mnie można tak zrobić.  Kod wydaje się ok.

2023-05-02 13:48 UTC, kujawapatryk requested changes

2023-05-02 13:48 UTC, kujawapatryk commented on routers/student.router.ts
> -import {Request, Response, Router} from "express";
ten import powinien zostac

2023-05-02 13:48 UTC, kujawapatryk commented on types/student/student.entity.ts
> +export interface filterData {
Nazwy interfejsów daj od dużej litery.

2023-05-02 14:28 UTC, kujawapatryk requested changes
Dane z filtrowania nigdy nie będą undefined, ponieważ w formularzu po zostawieniu pustego pola  generowany jest jest ''

2023-05-02 14:28 UTC, kujawapatryk commented on records/student.record.ts
> +    } else if (max !== undefined) {
ten if jest nie potrzeby możesz wykorzystać between z formularza powinno być zwrócone 0

2023-05-02 14:32 UTC, kujawapatryk commented
więcej sie nie będę czepiał xD jeśli jeszcze będzie modyfikowane

2023-05-05 09:02 UTC, git-asia commented
Task linked: [CU-862jq9qw1 BE. Dane do wyświetlenia studentów 8h](https://app.clickup.com/t/862jq9qw1)

2023-05-11 13:13 UTC, merged