Cu 862jpf6vu be walidacja danych w klasie student 7h michu
git-asia/HeadHunter_server pull request #20
Opened 2023-05-02 08:56 UTC by mich-dem

2023-05-02 13:25 UTC, kujawapatryk requested changes
Jak instalowałeś sobie BE to coś jeszcze modyfikowałeś w eslint lub prettier?
Bo widzę że jest dużo zmian w już istniejącym kodzie gdzie została dodana/usunięta spacja i zastanawiam się skąd to wynika.

2023-05-02 13:25 UTC, kujawapatryk commented on records/hr.record.ts
> +import {HrEntity} from "../types";
W poprzednim pull request tez masz ten plik wiec te same poprawki co tam

2023-05-02 13:25 UTC, kujawapatryk commented on records/student.record.ts
> +  expectedSalary: '' | number;
Co oznacza  ' ' | number  ? (liczba lub ?)

2023-05-02 13:25 UTC, kujawapatryk commented on records/student.record.ts
> +    const phoneRegex = /(?:(?:(?:\+|00)?48)|(?:\(\+?48\)))?(?:1[2-8]|2[2-69]|3[2-49]|4[1-8]|5[0-9]|6[0-35-9]|[7-8][1-9]|9[145])\d{7}/
nie ograniczałbym tylko do polskich numerów.

2023-05-02 13:25 UTC, kujawapatryk commented on types/hr/hr.entity.ts
> +    email: string;
email

2023-05-02 13:51 UTC, mich-dem commented on records/student.record.ts
> +    const phoneRegex = /(?:(?:(?:\+|00)?48)|(?:\(\+?48\)))?(?:1[2-8]|2[2-69]|3[2-49]|4[1-8]|5[0-9]|6[0-35-9]|[7-8][1-9]|9[145])\d{7}/
Poprawiłem

2023-05-02 14:29 UTC, mich-dem commented on records/hr.record.ts
> +import {HrEntity} from "../types";
Usunąłem

2023-05-02 14:29 UTC, mich-dem commented on types/hr/hr.entity.ts
> +    email: string;
Usunąłem

2023-05-06 21:10 UTC, git-asia commented
Task linked: [CU-862jpf6vu BE: walidacja danych w klasie student 7h](https://app.clickup.com/t/862jpf6vu)

2023-05-06 22:17 UTC, merged