Added validation
git-asia/HeadHunter_server pull request #27
Opened 2023-05-10 15:20 UTC by mich-dem

2023-05-10 15:21 UTC, git-asia commented
Task linked: [CU-862jruqpy BE: Edycja danych studenta](https://app.clickup.com/t/862jruqpy)

2023-05-11 13:28 UTC, kujawapatryk commented
Nie łatwiej byłoby z otrzymanych danych stworzyć rekord StudentRecord i wtedy wykorzystać walidacje danych rekordu i wywołać zapytanie do bazy? Bo w tej chwili trochę powtarzamy istniejący kod

2023-05-11 13:29 UTC, kujawapatryk requested changes
Nie łatwiej byłoby z otrzymanych danych stworzyć rekord StudentRecord i wtedy wykorzystać walidacje danych rekordu i wywołać zapytanie do bazy? Bo w tej chwili trochę powtarzamy istniejący kod

2023-05-13 23:49 UTC, mich-dem commented
> 

Poprawiłem

2023-05-16 23:09 UTC, merged